name: GitHub actions demo
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
      - name: Output build
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.ref_name }}
          echo "Listing all files in the repository:"
            ls -al
        

