name: GitHub actions demo
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
      - name: Output build
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.ref_name }}
          echo "Listing all files in the repository:"
            ls -al
        

